### ISSUE TITLE
Can't connect to mongo docker

### ISSUE THREAD

**Issue by galvakojis** [frankie567/fastapi-users#162]
okey, spend a day, but still can't make this work

> .env

```
# Mongo DB
MONGO_INITDB_ROOT_USERNAME=admin-user
MONGO_INITDB_ROOT_PASSWORD=admin-password
MONGO_INITDB_DATABASE=container
```

> docker-compose.yml

```
 mongo-db:
    image: mongo:4.2.3
    env_file:
      - .env
    ports:
      - 27017:27107
    volumes:
      - ./bin/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #    restart: always add this production


  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8006 --reload
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - mongo-db
    ports:
      - "8006:8006"
```

> mongo-init.js

```
db.auth('admin-user', 'admin-password')

db = db.getSiblingDB('container')

db.createUser({
    user: 'test-user',
    pwd: 'test-password',
    roles: [
        {
            role: 'root',
            db: 'admin',
        },
    ],
});

```
using this as example - https://frankie567.github.io/fastapi-users/configuration/full_example/

changed few lines:
`DATABASE_URL = "mongodb://test-user:test-password@mongo-db/container"`
```
client = motor.motor_asyncio.AsyncIOMotorClient(DATABASE_URL)
db = client["container"]
collection = db["users"]
user_db = MongoDBUserDatabase(UserDB, collection)
```
so think Fatapi is linked to Mongo container
![image](https://user-images.githubusercontent.com/17315578/80109217-e78acf80-8585-11ea-9008-2dcfb4de3667.png)

but when i try to register user using Fastapi docks section, i get 
"Internal server error"

what I left unfinished?
